name: White Paper
description: >
    A simple jekyll theme aimed at programmers who like clean interface to write posts
    and show off some code.
about: >
    Todo.

master_repo: true
url: "http://geeeljay.github.io/blog"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           whitepaper
  avatar:         "https://avatars1.githubusercontent.com/u/537678?s=240&v=4"
  email:          "vinit1414.08@bitmesra.ac.in"
  # Social networking links used in footer. Update and remove as you like.
  twitter: 
  github: https://github.com/geeeljay
  stackexchange: 
  linkedin: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
